# Site settings
title: AFrame
description: "Highly maintainable automation framework."
baseurl: ""
url: "https://aframe.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

author:
  name: Sam Thwaites