# Site settings
title: AFrame
description: "Highly maintainable automation framework."
baseurl: ""
url: "https://aframe.github.io"

# Build settings
markdown: rdiscount
permalink: pretty
highlighter: pygments

author:
  name: Sam Thwaites